all:
	g++ -fPIC -shared res/ErosServlet.h src/ErosServletExample.h src/ErosServletExample.cpp -o war/ErosServletExample.so
	g++ -fPIC -shared res/ErosServlet.h src/myapp.h src/myapp.cpp -o war/myapp.so